name: release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build the Python distribution
        run: |
          uv build
      - name: Publish the Python distributions to PyPI
        run: |
          uv publish --trusted-publishing=always

  publish-python-client:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build the Python distribution
        run: |
          uv build
        working-directory: python-client
      - name: Publish the Python distributions to PyPI
        run: |
          uv publish --trusted-publishing=always
        working-directory: python-client

  publish-javascript-client:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: current
      - name: Publish Javascript client to npm
        working-directory: ./javascript-client
        run: |
          npm ci
          npm version --no-git-tag-version $(git describe --tags --match '*[0-9]*' --abbrev=0 | sed 's/^v//')
          npm publish --provenance
