name: release
on:
  release:
    types: [published]
jobs:
  publish-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: "true"
        run: |
          tox -e release
      - name: Publish Python client to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.CLIENT_PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: "true"
        working-directory: ./python-client
        run: |
          tox -e release
  publish-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
      - name: Publish Javascript client to npm
        working-directory: ./javascript-client
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm version --no-git-tag-version $(git describe --tags --match '*[0-9]*' --abbrev=0 | sed 's/^v//')
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc
          npm publish
